#! /bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

while getopts "hd:uirt:l" OPTION; do
    case $OPTION in
        h )
            echo -e "\n${YELLOW}Help${NC}\n"

            echo -e "${BLUE}d${NC} - Target directory"
            echo -e "${BLUE}u${NC} - Update code using git pull"
            echo -e "${BLUE}i${NC} - Install dependencies using composer"
            echo -e "${BLUE}r${NC} - Refresh laravel instance and fix folder permission / ownership"
            echo -e "${BLUE}t${NC} - Output Laravel log file with specified line number (eg: -t 100 to output last 100 line)"
            echo -e "${BLUE}l${NC} - Output Laravel log file and append output as log file grow"
            exit 0
            ;;
        d )
            DEPLOY_DIR="$OPTARG"
            ;;
    esac
done

if [[ -z "${DEPLOY_DIR}" ]]; then
    read -p "Use current folder $PWD? [y/n] " YN

    if [[ $YN == "y" || $YN == "Y" ]]; then
        DEPLOY_DIR="$PWD"
    else
        echo -e "\nExiting..."
        exit 1
    fi
else
    DEPLOY_DIR="${DEPLOY_DIR}"
fi

pushd $DEPLOY_DIR

while getopts "hd:uirt:l" OPTION; do
    case $OPTION in
    u )
        echo -e "\n${YELLOW}Updating code in $DEPLOY_DIR${NC}\n"
        git pull
        ;;
    i )
        echo -e "\n${YELLOW}Installing dependencies${NC}\n"
        composer install
        ;;
    r )
        echo -e "${YELLOW}Refresh laravel instance${NC}\n"
        composer dump-autoload && php artisan cache:clear && php artisan config:clear && php artisan view:clear && php artisan config:cache && php artisan queue:restart
        echo -e "${YELLOW}Reset folder permissions${NC}\n"
        chown -R www-data:www-data . && chmod -R 755 storage && chmod -R 755 bootstrap/cache
        ;;
    t )
        echo -e "\n${YELLOW}Laravel log${NC}\n"
        tail -n $OPTARG storage/logs/laravel-$(date +%Y-%m-%d).log
        ;;
    l )
        echo -e "\n${YELLOW}Laravel log${NC}\n"
        tail -f storage/logs/laravel-$(date +%Y-%m-%d).log
        ;;
    esac
done

popd
